### PR TITLE
Added more reference to Readme.MD

### PR DESCRIPTION
**Pull request by HexagonStudio**
Hi,

I just added the openhouse, listingids and referencenumber to the options in readme.md. Thank you for this package!

### CODE REVIEW

**Comment by Froren** [comment]
Thanks for the contribution @HexagonStudio ! That's super useful. Also happy to hear you find the library helpful.

To conform to the rest of the params as a stylistic change, can we use `listingIds` or `ListingIds`? 
I've confirmed that it works and I want to match the camel casing of the other options.

**Comment by HexagonStudio** [comment]
Yes, I just tested it and `listingids` works as well

**Comment by Froren** [comment]
Can you revise the PR to capitalize `Id`?

**Comment by HexagonStudio** [comment]
Just pushed it.

**Pull request merged**
